# Generated by Django 5.2.17 on 2026-09-30 15:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Throttle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('bucket', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=50)),
                ('recovery_hash', models.CharField(max_length=256)),
                ('resume', models.TextField(blank=True, max_length=20000)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=150)),
                ('source_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(max_length=20000)),
                ('requirements', models.TextField(blank=True, help_text='Optional: one skill phrase per line. Overrides automatic skill detection. Maximum 30 phrases.', max_length=3000)),
                ('stage', models.CharField(choices=[('saved', 'Saved'), ('applied', 'Applied'), ('screening', 'Screening'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='saved', max_length=12)),
                ('next_step', models.CharField(blank=True, max_length=300)),
                ('due', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, max_length=3000)),
                ('submission_id', models.UUIDField(blank=True, editable=False, null=True)),
                ('submission_hash', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated'],
                'indexes': [models.Index(fields=['owner', 'stage'], name='tracker_app_owner_i_8b00e4_idx'), models.Index(fields=['owner', 'due'], name='tracker_app_owner_i_c98e6e_idx')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'submission_id'), name='application_submission_unique'), models.CheckConstraint(condition=models.Q(('stage__in', ['saved', 'applied', 'screening', 'interview', 'offer', 'rejected', 'withdrawn'])), name='application_stage_valid')],
            },
        ),
    ]
