# Generated by Django 5.2.17 on 2026-09-30 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedState',
            fields=[
                ('key', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('attempted', models.DateTimeField(null=True)),
                ('success', models.DateTimeField(null=True)),
                ('error', models.CharField(blank=True, max_length=80)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_key', models.CharField(max_length=180, unique=True)),
                ('provider', models.CharField(max_length=20)),
                ('board', models.CharField(max_length=80)),
                ('company', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=150)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(max_length=20000)),
                ('url', models.URLField(max_length=500)),
                ('role', models.CharField(max_length=20)),
                ('level', models.CharField(max_length=20)),
                ('workplace', models.CharField(max_length=20)),
                ('salary', models.TextField(blank=True, max_length=1000)),
                ('evidence', models.JSONField(default=dict)),
                ('source_updated', models.CharField(blank=True, max_length=50)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('checked', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-first_seen', 'pk'],
                'indexes': [models.Index(fields=['active', 'role'], name='tracker_job_active_8f257a_idx'), models.Index(fields=['company', 'board'], name='tracker_job_company_6ce52f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResumeDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField(default=dict)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('filters', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('seen', models.DateTimeField(null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
