# Generated by Django 5.2.17 on 2026-10-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_feedstate_job_resumedraft_savedsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=100000),
        ),
    ]
